### test
name: runner

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: test manifests folder
      uses: instrumenta/kubeval-action@master
      with: 
       files: manifests
